/**
 * Use these variables when you tailor your ArkTS code. They must be of the const type.
 */
export declare const HAR_VERSION = "1.1.3";
export declare const BUILD_MODE_NAME = "release";
export declare const DEBUG = false;
export declare const TARGET_NAME = "default";
export declare const HAR_VERSION_CODE = 10103;
export declare const IS_TOB = true;
/**
 * BuildProfile Class is used only for compatibility purposes.
 */
export default class BuildProfile {
    static readonly HAR_VERSION = "1.1.3";
    static readonly BUILD_MODE_NAME = "release";
    static readonly DEBUG = false;
    static readonly TARGET_NAME = "default";
    static readonly HAR_VERSION_CODE = 10103;
    static readonly IS_TOB = true;
}
