export declare class DeviceInfo {
    private static readonly _os_version;
    private static readonly _os;
    static get os(): string;
    private static readonly _rom_version;
    static get rom_version(): string;
    private static readonly _rom;
    static get rom(): string;
    private static readonly _cpu_abi;
    static get cpu_abi(): string;
    private static readonly _brand;
    static get brand(): string;
    private static readonly _os_api;
    static get os_api(): number;
    private static readonly _manufacture;
    static get manufacture(): string;
    private static readonly _device_model;
    static get device_model(): string;
    private static readonly _brand_model;
    static get brand_model(): string;
    static get os_version(): string;
    private static readonly _hardware;
    static get hardware(): string;
}
export default DeviceInfo;
