/**
 * @detail keytype
 * @brief 群组角色。
 */
export declare enum BIMMemberRole {
    /**
     * @hidden
     * @brief 未知成员。
     */
    BIM_MEMBER_ROLE_UNKNOWN = -1,
    /**
     * @brief 普通成员。
     */
    BIM_MEMBER_ROLE_NORMAL = 0,
    /**
     * @brief 群主。
     */
    BIM_MEMBER_ROLE_OWNER = 1,
    /**
     * @brief 管理员。
     */
    BIM_MEMBER_ROLE_ADMIN = 2,
    /**
     * @brief 游客。
     */
    BIM_MEMBER_ROLE_VISITOR = 3
}
