export const DEFAULT_TABLE = "DEFAULT"; export const EVENT_TABLE = "EVENT"; export const DEFAULT_DB_VERSION = 0; export const COL_ID = "id"; export const COL_EVENT_TYPE = "event_type"; export const COL_EVENT_NAME = "event_name"; export const COL_TS = "local_time_ms"; export const COL_LOCAL_EVENT_ID = "event_local_id"; export const COL_SESSION_ID = "session_id"; export const COL_APP_ID = "app_id"; export const COL_SDK_INSTANCE_KEY = "sdk_instance_key"; export const COL_EXTERNAL_FIELDS = "external_fields"; export const COL_CUSTOM_PARAM = "custom_param"; export const COL_USER_PARAM = "user_param"; export const COL_SSID = "ssid"; export function createTableV1(q12) { return `CREATE TABLE IF NOT EXISTS ${q12} (${COL_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
${COL_EVENT_TYPE} INTEGER,
${COL_EVENT_NAME} TEXT NOT NULL,
${COL_TS} INTEGER,
${COL_LOCAL_EVENT_ID} INTEGER,
${COL_SESSION_ID} INTEGER,
${COL_APP_ID} TEXT NOT NULL,
${COL_SDK_INSTANCE_KEY} TEXT NOT NULL,
${COL_EXTERNAL_FIELDS} TEXT,
${COL_CUSTOM_PARAM} TEXT,
${COL_USER_PARAM} TEXT,
${COL_SSID} TEXT)`; } 