export declare class LiveReceiverMsgMetricsModel {
    msgServerId: string;
    recieve_start_time: number;
    send_start_time: number;
    recieve_end_time: number;
    recieve_cost_time: number;
    load_cost_time: number;
    total_cost_time: number;
    pull_msg_reaseon: number;
    sTime: number;
    sEndTime: number;
    end_end_cost: number;
    isWs: boolean;
    logId: string;
}
